const DECLARATION = [
  {
    id: "684d24293c37d4baf9a52c43",
    index: 0,
    guid: "e52b311e-5845-4dde-951d-391b9fb3e998",
    isActive: true,
    status: "ON_GOING",
    balance: "$2,336.54",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "blue",
    name: "Beatrice Sparks",
    gender: "female",
    company: "TUBALUM",
    email: "beatricesparks@tubalum.com",
    phone: "+1 (838) 591-3173",
    address: "237 Albany Avenue, Twilight, California, 8825",
    about:
      "Sit non velit consequat amet. Et Lorem eu fugiat officia ipsum duis. Occaecat laboris veniam mollit eiusmod et pariatur. Sint ea sint ipsum labore ad laboris do id et elit culpa. Occaecat pariatur voluptate dolor laborum cillum enim.\r\n",
    registered: "2023-09-02T02:07:33 -02:00",
    latitude: -64.393796,
    longitude: -44.605969,
    tags: ["duis", "mollit", "sunt", "magna", "aute", "mollit", "anim"],
    friends: [
      {
        id: 0,
        name: "Mckee Banks",
      },
      {
        id: 1,
        name: "Myrtle Harrington",
      },
      {
        id: 2,
        name: "Vargas Berg",
      },
    ],
    greeting: "Hello, Beatrice Sparks! You have 8 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    id: "684d2429be867c5efecfffcd",
    index: 1,
    guid: "2381b710-34a1-4f9a-a41e-359571c51b7b",
    isActive: false,
    status: "VALIDATED",
    balance: "$3,876.41",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "brown",
    name: "Elva Mathis",
    gender: "female",
    company: "NETUR",
    email: "elvamathis@netur.com",
    phone: "+1 (953) 567-2365",
    address: "131 Just Court, Blackgum, Maine, 2941",
    about:
      "Ea irure magna exercitation ullamco exercitation velit consequat id aliqua minim aliqua deserunt cillum cillum. Elit nulla ad aute incididunt est quis cillum excepteur cupidatat. Commodo non magna veniam laborum ex dolor officia nulla tempor. Cillum non reprehenderit veniam cupidatat occaecat do pariatur do eu aliqua laboris aute culpa nostrud. Aliquip cupidatat Lorem esse sint consequat nulla nisi. Et minim enim quis deserunt cupidatat ea incididunt veniam amet esse nostrud pariatur officia.\r\n",
    registered: "2025-05-26T10:33:44 -02:00",
    latitude: -22.455125,
    longitude: -46.776492,
    tags: [
      "eu",
      "ullamco",
      "pariatur",
      "est",
      "adipisicing",
      "nostrud",
      "labore",
    ],
    friends: [
      {
        id: 0,
        name: "Graham Espinoza",
      },
      {
        id: 1,
        name: "Gwen Brady",
      },
      {
        id: 2,
        name: "Lottie Cash",
      },
    ],
    greeting: "Hello, Elva Mathis! You have 8 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    id: "684d2429788fea637d17c113",
    index: 2,
    guid: "b5ac4f41-b17e-445c-b913-0c89aaad6ea2",
    isActive: false,
    status: "VALIDATED",
    balance: "$3,660.19",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "blue",
    name: "Love Robertson",
    gender: "male",
    company: "VORTEXACO",
    email: "loverobertson@vortexaco.com",
    phone: "+1 (855) 523-2147",
    address: "810 Bijou Avenue, Tilleda, Georgia, 8808",
    about:
      "Laborum reprehenderit velit non reprehenderit culpa voluptate. Cillum consectetur non veniam qui amet occaecat veniam sint laboris ipsum. Culpa ex sint magna pariatur Lorem amet mollit laborum in incididunt. Ex minim voluptate ullamco excepteur est non nostrud proident in consequat Lorem exercitation veniam cillum. Deserunt incididunt commodo mollit nostrud adipisicing Lorem ut et Lorem sit.\r\n",
    registered: "2019-10-14T12:31:45 -02:00",
    latitude: 0.87562,
    longitude: -154.963487,
    tags: ["qui", "ipsum", "officia", "sint", "qui", "tempor", "nostrud"],
    friends: [
      {
        id: 0,
        name: "Burgess Stanley",
      },
      {
        id: 1,
        name: "Albert Emerson",
      },
      {
        id: 2,
        name: "Best Perkins",
      },
    ],
    greeting: "Hello, Love Robertson! You have 3 unread messages.",
    favoriteFruit: "apple",
  },
  {
    id: "684d2429aaeeecae07ee86d1",
    index: 3,
    guid: "39595eba-98dd-44b1-97ef-d2db5b1b9c1b",
    isActive: true,
    status: "REJECTED",
    balance: "$1,853.11",
    picture: "http://placehold.it/32x32",
    age: 24,
    eyeColor: "green",
    name: "Noelle Bell",
    gender: "female",
    company: "EXTRAGENE",
    email: "noellebell@extragene.com",
    phone: "+1 (836) 582-3139",
    address: "624 Irvington Place, Sperryville, Oregon, 8445",
    about:
      "Irure incididunt ipsum veniam sunt quis. Fugiat veniam dolor consectetur voluptate nulla quis reprehenderit qui sunt eiusmod anim in occaecat. Sint occaecat anim mollit commodo voluptate id culpa esse enim voluptate consectetur. Mollit dolor nisi ex minim eiusmod non ea occaecat culpa. Ex quis qui in non aute aute. Minim fugiat quis exercitation pariatur laboris qui duis eiusmod pariatur ea exercitation sit est laboris.\r\n",
    registered: "2021-05-22T07:41:15 -02:00",
    latitude: -2.577897,
    longitude: -44.043515,
    tags: [
      "anim",
      "eiusmod",
      "incididunt",
      "ullamco",
      "exercitation",
      "exercitation",
      "veniam",
    ],
    friends: [
      {
        id: 0,
        name: "Wiggins Carney",
      },
      {
        id: 1,
        name: "Bender Knight",
      },
      {
        id: 2,
        name: "Decker Edwards",
      },
    ],
    greeting: "Hello, Noelle Bell! You have 7 unread messages.",
    favoriteFruit: "apple",
  },
  {
    id: "684d24290b7965896facbe42",
    index: 4,
    guid: "3f50c355-5781-4c7f-8167-3b8021351bc2",
    isActive: true,
    status: "ON_GOING",
    balance: "$2,248.33",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "green",
    name: "Celia Burt",
    gender: "female",
    company: "BUZZOPIA",
    email: "celiaburt@buzzopia.com",
    phone: "+1 (802) 411-3647",
    address: "875 Exeter Street, Rockhill, Wyoming, 7445",
    about:
      "Cupidatat amet amet consectetur est ullamco labore qui consectetur commodo. Aliqua pariatur fugiat aliqua Lorem commodo cillum. Est tempor qui laborum consectetur ipsum. Incididunt est nulla fugiat eu ad exercitation pariatur deserunt aliqua elit ad laboris proident. Pariatur officia incididunt aute officia quis velit labore ad velit incididunt eu. Proident veniam fugiat commodo ipsum. Exercitation do ut enim consequat nisi sunt ad id esse Lorem.\r\n",
    registered: "2017-11-03T07:53:23 -01:00",
    latitude: 34.245704,
    longitude: -58.5786,
    tags: [
      "deserunt",
      "adipisicing",
      "mollit",
      "occaecat",
      "aliquip",
      "irure",
      "magna",
    ],
    friends: [
      {
        id: 0,
        name: "Farmer Ross",
      },
      {
        id: 1,
        name: "Jacobson Caldwell",
      },
      {
        id: 2,
        name: "Marissa Mayo",
      },
    ],
    greeting: "Hello, Celia Burt! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "684d242917f5a879e204279a",
    index: 5,
    guid: "29381bd8-6beb-47f4-9fa0-df4bba2bf9e9",
    isActive: false,
    status: "ON_GOING",
    balance: "$2,476.81",
    picture: "http://placehold.it/32x32",
    age: 22,
    eyeColor: "blue",
    name: "Reid Flores",
    gender: "male",
    company: "MEDALERT",
    email: "reidflores@medalert.com",
    phone: "+1 (942) 548-2493",
    address: "168 Danforth Street, Esmont, Utah, 6339",
    about:
      "Ipsum consectetur officia non elit. Aliqua pariatur tempor ex sunt officia anim consectetur Lorem cupidatat nulla ad. Irure anim non id elit consectetur cillum mollit dolore sunt adipisicing amet nisi. Et laboris Lorem aliqua id velit deserunt ea Lorem cupidatat esse aliqua. Ullamco consectetur in commodo laboris deserunt velit incididunt aliqua laborum mollit in sint. Nostrud esse non ex excepteur commodo commodo velit aute officia fugiat est sunt irure do. Eu nostrud adipisicing veniam id quis amet esse enim tempor velit nostrud et.\r\n",
    registered: "2014-09-18T06:46:38 -02:00",
    latitude: 51.262285,
    longitude: 109.233629,
    tags: ["nostrud", "anim", "minim", "aute", "officia", "aliquip", "aute"],
    friends: [
      {
        id: 0,
        name: "Nielsen Gamble",
      },
      {
        id: 1,
        name: "Kristine Hester",
      },
      {
        id: 2,
        name: "Bruce Wilcox",
      },
    ],
    greeting: "Hello, Reid Flores! You have 10 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    id: "684d2429f2aaee1b32d9effe",
    index: 6,
    guid: "2759eb79-762e-4541-838f-e0cb4b1a2746",
    isActive: false,
    status: "ON_GOING",
    balance: "$2,078.92",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "blue",
    name: "Preston Gray",
    gender: "male",
    company: "FISHLAND",
    email: "prestongray@fishland.com",
    phone: "+1 (863) 594-2644",
    address: "180 Brevoort Place, Defiance, Alaska, 7930",
    about:
      "Quis ipsum aute aliqua in exercitation anim cupidatat laborum ex sint. Tempor sunt pariatur ad nulla qui ullamco anim. Deserunt sunt cillum id aliqua.\r\n",
    registered: "2021-12-30T12:43:20 -01:00",
    latitude: 55.952349,
    longitude: 172.440914,
    tags: [
      "incididunt",
      "voluptate",
      "fugiat",
      "eiusmod",
      "excepteur",
      "nulla",
      "elit",
    ],
    friends: [
      {
        id: 0,
        name: "Jannie Russell",
      },
      {
        id: 1,
        name: "Daugherty Bean",
      },
      {
        id: 2,
        name: "Jeanne Vazquez",
      },
    ],
    greeting: "Hello, Preston Gray! You have 4 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "684d242965493fdfdc182c47",
    index: 7,
    guid: "35e3b461-2978-4dac-83b9-385fc69d2dc6",
    isActive: false,
    status: "NEW",
    balance: "$1,665.43",
    picture: "http://placehold.it/32x32",
    age: 27,
    eyeColor: "green",
    name: "Stephenson Jackson",
    gender: "male",
    company: "SCHOOLIO",
    email: "stephensonjackson@schoolio.com",
    phone: "+1 (836) 591-2613",
    address: "620 Varick Avenue, Catherine, Puerto Rico, 9184",
    about:
      "Sit officia velit sit sint culpa tempor ut voluptate magna tempor mollit anim veniam cupidatat. Proident ad voluptate sit voluptate ullamco minim elit commodo labore duis proident. Sit consequat fugiat cupidatat laborum Lorem. Fugiat minim qui non ex ad officia sunt esse irure nulla proident aute. Nulla incididunt minim id proident deserunt exercitation.\r\n",
    registered: "2023-03-03T09:36:23 -01:00",
    latitude: -87.427232,
    longitude: -17.903907,
    tags: ["amet", "nostrud", "amet", "sint", "mollit", "tempor", "est"],
    friends: [
      {
        id: 0,
        name: "Odessa Francis",
      },
      {
        id: 1,
        name: "Linda Conner",
      },
      {
        id: 2,
        name: "Zamora Jordan",
      },
    ],
    greeting: "Hello, Stephenson Jackson! You have 3 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    id: "684d24291785c8b4dcba9bf9",
    index: 8,
    guid: "89b94e91-c397-42e3-960a-cdff841aab3a",
    isActive: true,
    status: "NEW",
    balance: "$1,063.08",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "green",
    name: "Cantu Holcomb",
    gender: "male",
    company: "SENTIA",
    email: "cantuholcomb@sentia.com",
    phone: "+1 (995) 594-2443",
    address: "837 Falmouth Street, Sparkill, American Samoa, 7495",
    about:
      "Sunt reprehenderit proident occaecat excepteur labore eu pariatur labore culpa magna. Exercitation minim minim cillum officia officia mollit enim eu proident quis amet nostrud consequat cillum. Ullamco dolor eu laborum adipisicing irure labore nulla exercitation. Ea deserunt elit deserunt magna ullamco ipsum. Fugiat laboris exercitation labore ipsum cillum qui.\r\n",
    registered: "2015-05-19T01:27:18 -02:00",
    latitude: -4.414515,
    longitude: -33.087042,
    tags: ["magna", "dolore", "eiusmod", "aliqua", "quis", "anim", "labore"],
    friends: [
      {
        id: 0,
        name: "Dixon Barber",
      },
      {
        id: 1,
        name: "Marie Rojas",
      },
      {
        id: 2,
        name: "Whitley Oliver",
      },
    ],
    greeting: "Hello, Cantu Holcomb! You have 7 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    id: "684d24291ff72fe670a5e6f8",
    index: 9,
    guid: "f7ba1baf-a48d-4018-80d3-2d5129d12611",
    isActive: true,
    status: "VALIDATED",
    balance: "$2,293.87",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "green",
    name: "Atkinson Dalton",
    gender: "male",
    company: "PUSHCART",
    email: "atkinsondalton@pushcart.com",
    phone: "+1 (819) 448-2154",
    address: "808 Lester Court, Hannasville, New Jersey, 3303",
    about:
      "Officia sint officia labore aliqua cupidatat voluptate id. Non reprehenderit nisi occaecat nisi anim pariatur aliqua ut cupidatat cupidatat et nostrud ea aute. Aliqua do tempor minim velit exercitation elit duis minim consequat ipsum dolor incididunt voluptate eiusmod. Proident Lorem non do aute dolor consequat nostrud veniam mollit quis culpa adipisicing adipisicing. Dolor mollit ex in veniam reprehenderit. Commodo quis deserunt do anim laborum et sunt dolor.\r\n",
    registered: "2021-06-05T03:04:51 -02:00",
    latitude: 79.186115,
    longitude: 109.515736,
    tags: ["pariatur", "sint", "eu", "aute", "proident", "commodo", "eiusmod"],
    friends: [
      {
        id: 0,
        name: "Esperanza Roman",
      },
      {
        id: 1,
        name: "Reynolds Hartman",
      },
      {
        id: 2,
        name: "Fox Summers",
      },
    ],
    greeting: "Hello, Atkinson Dalton! You have 3 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "684d2429234a538a4afd26a1",
    index: 10,
    guid: "eb727664-5cda-4b17-bc78-f01edeb297c5",
    isActive: false,
    status: "ON_GOING",
    balance: "$3,285.41",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "blue",
    name: "Workman Fry",
    gender: "male",
    company: "PLASMOS",
    email: "workmanfry@plasmos.com",
    phone: "+1 (814) 463-2663",
    address: "577 Bergen Street, Trinway, Virgin Islands, 8782",
    about:
      "Est consequat incididunt tempor fugiat culpa ut quis tempor. Culpa irure enim eu sit qui minim sunt sunt est nisi ipsum aliqua qui. Est voluptate pariatur elit dolore esse. Tempor enim voluptate occaecat adipisicing deserunt id esse. Reprehenderit ut eiusmod cupidatat nulla elit consectetur et. Labore occaecat officia voluptate pariatur pariatur enim nostrud tempor quis Lorem dolore.\r\n",
    registered: "2014-04-23T10:09:01 -02:00",
    latitude: 44.730427,
    longitude: -29.845012,
    tags: [
      "officia",
      "pariatur",
      "cillum",
      "deserunt",
      "sit",
      "amet",
      "laborum",
    ],
    friends: [
      {
        id: 0,
        name: "Mcgee Cochran",
      },
      {
        id: 1,
        name: "Antonia Price",
      },
      {
        id: 2,
        name: "Pamela Adkins",
      },
    ],
    greeting: "Hello, Workman Fry! You have 8 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "684d2429b6c6fe628999df73",
    index: 11,
    guid: "6e3efdbb-fe64-4c23-891e-2931cb752e36",
    isActive: true,
    status: "NEW",
    balance: "$2,292.33",
    picture: "http://placehold.it/32x32",
    age: 22,
    eyeColor: "blue",
    name: "Emilia Mack",
    gender: "female",
    company: "BARKARAMA",
    email: "emiliamack@barkarama.com",
    phone: "+1 (870) 439-3677",
    address: "490 Jodie Court, Fowlerville, Michigan, 5933",
    about:
      "Nulla nisi fugiat amet esse cupidatat. Id est aute qui proident voluptate sint excepteur ad sint magna qui sint. Irure sit ut Lorem sit velit nostrud velit consectetur non labore velit deserunt. Ipsum officia fugiat non in mollit amet id. Occaecat adipisicing elit fugiat esse proident sunt aliquip. Duis deserunt excepteur et in. Exercitation excepteur ipsum minim deserunt.\r\n",
    registered: "2024-08-19T06:09:26 -02:00",
    latitude: -26.120051,
    longitude: -35.930151,
    tags: ["qui", "voluptate", "quis", "ad", "est", "veniam", "anim"],
    friends: [
      {
        id: 0,
        name: "Tina Cooke",
      },
      {
        id: 1,
        name: "Davis Franklin",
      },
      {
        id: 2,
        name: "Vang Wright",
      },
    ],
    greeting: "Hello, Emilia Mack! You have 3 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "684d2429cae36860bb0799a4",
    index: 12,
    guid: "c95d72c8-9b48-44d5-8055-215268b5d8dc",
    isActive: false,
    status: "NEW",
    balance: "$2,480.38",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "blue",
    name: "Angelia Murray",
    gender: "female",
    company: "QUARX",
    email: "angeliamurray@quarx.com",
    phone: "+1 (976) 449-2567",
    address: "406 Bushwick Place, Ferney, Oklahoma, 8056",
    about:
      "Minim nisi sunt enim laborum officia occaecat ipsum nulla aliquip. Cillum ut ipsum ea nulla culpa adipisicing. Officia ut excepteur incididunt voluptate. Culpa ex ipsum nulla occaecat dolore sint dolor proident ea ex tempor mollit esse. Ea ullamco cupidatat in aliqua quis consequat adipisicing veniam. Proident qui reprehenderit ullamco aliqua pariatur consequat sit non ad anim. Excepteur culpa deserunt magna proident ipsum nulla ad magna.\r\n",
    registered: "2014-08-21T03:29:06 -02:00",
    latitude: -84.29965,
    longitude: 100.930185,
    tags: ["officia", "proident", "anim", "adipisicing", "qui", "do", "velit"],
    friends: [
      {
        id: 0,
        name: "Briggs Kidd",
      },
      {
        id: 1,
        name: "Boyd Lancaster",
      },
      {
        id: 2,
        name: "Shannon Drake",
      },
    ],
    greeting: "Hello, Angelia Murray! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "684d2429ee750f2542a4fb79",
    index: 13,
    guid: "ea12c470-4d80-47f1-8aad-d87d7dbed749",
    isActive: false,
    status: "NEW",
    balance: "$2,596.88",
    picture: "http://placehold.it/32x32",
    age: 28,
    eyeColor: "brown",
    name: "Miller Moore",
    gender: "male",
    company: "VURBO",
    email: "millermoore@vurbo.com",
    phone: "+1 (860) 526-3837",
    address: "971 Wogan Terrace, Hiwasse, Nevada, 2897",
    about:
      "Sit eiusmod elit sunt sit amet fugiat labore dolor ad ipsum. Esse do sit ex eiusmod excepteur aliquip. Excepteur cupidatat eiusmod occaecat elit enim eu adipisicing ut dolore laborum id Lorem. Consequat aute sit quis irure nulla.\r\n",
    registered: "2023-03-03T11:42:28 -01:00",
    latitude: 76.96613,
    longitude: 24.970837,
    tags: ["do", "reprehenderit", "sint", "quis", "non", "tempor", "tempor"],
    friends: [
      {
        id: 0,
        name: "Tami Stevens",
      },
      {
        id: 1,
        name: "Allyson Cotton",
      },
      {
        id: 2,
        name: "Shari Rice",
      },
    ],
    greeting: "Hello, Miller Moore! You have 2 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    id: "684d242965a74bf1756f94dd",
    index: 14,
    guid: "9d2a13db-1947-4c04-b110-8cebed57ad73",
    isActive: true,
    status: "ON_GOING",
    balance: "$3,172.60",
    picture: "http://placehold.it/32x32",
    age: 23,
    eyeColor: "green",
    name: "Tamera Ayala",
    gender: "female",
    company: "FLYBOYZ",
    email: "tameraayala@flyboyz.com",
    phone: "+1 (942) 403-3096",
    address: "601 Atlantic Avenue, Cartwright, Colorado, 9168",
    about:
      "Dolor elit fugiat magna ipsum do sit veniam. Pariatur sunt culpa enim deserunt veniam tempor. Tempor ex duis sunt consequat consequat adipisicing irure fugiat nisi est ipsum. Consequat laboris ex velit laboris pariatur sint occaecat excepteur fugiat fugiat aliqua consectetur incididunt.\r\n",
    registered: "2020-03-27T02:33:32 -01:00",
    latitude: -44.08858,
    longitude: -0.276431,
    tags: ["in", "sunt", "cillum", "dolore", "excepteur", "nisi", "laborum"],
    friends: [
      {
        id: 0,
        name: "Burt Dudley",
      },
      {
        id: 1,
        name: "Cunningham Nolan",
      },
      {
        id: 2,
        name: "Wilcox Burns",
      },
    ],
    greeting: "Hello, Tamera Ayala! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "684d2429414b22f8a9609a06",
    index: 15,
    guid: "5807e74d-25b5-4e0b-8217-ce6355d6cefb",
    isActive: true,
    status: "VALIDATED",
    balance: "$2,263.02",
    picture: "http://placehold.it/32x32",
    age: 20,
    eyeColor: "blue",
    name: "Madeleine Buckley",
    gender: "female",
    company: "FORTEAN",
    email: "madeleinebuckley@fortean.com",
    phone: "+1 (982) 511-2398",
    address: "169 Trucklemans Lane, Adamstown, Northern Mariana Islands, 4586",
    about:
      "Nulla nisi enim nostrud adipisicing nostrud ex consequat excepteur magna ut duis ut aliquip mollit. Ea eiusmod excepteur occaecat exercitation laborum qui nisi laborum adipisicing duis. Mollit aliqua esse sunt est officia aliquip non anim nisi nisi consectetur. Dolore aliquip anim commodo enim consectetur aute.\r\n",
    registered: "2022-03-19T09:13:58 -01:00",
    latitude: -1.181249,
    longitude: -114.418536,
    tags: [
      "eu",
      "exercitation",
      "mollit",
      "occaecat",
      "nisi",
      "culpa",
      "nostrud",
    ],
    friends: [
      {
        id: 0,
        name: "Gloria Lamb",
      },
      {
        id: 1,
        name: "Kristina Mcgee",
      },
      {
        id: 2,
        name: "Cline Santiago",
      },
    ],
    greeting: "Hello, Madeleine Buckley! You have 1 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    id: "684d24293f461863f06902e3",
    index: 16,
    guid: "f5ddfaae-848c-4b39-a83e-4e8b7f717eeb",
    isActive: true,
    status: "NEW",
    balance: "$3,828.77",
    picture: "http://placehold.it/32x32",
    age: 26,
    eyeColor: "green",
    name: "Cherry Chan",
    gender: "female",
    company: "VISUALIX",
    email: "cherrychan@visualix.com",
    phone: "+1 (875) 483-2788",
    address: "983 Seaview Court, Williston, Louisiana, 1712",
    about:
      "Nostrud consectetur do et tempor sunt fugiat culpa excepteur. Sunt excepteur irure sunt officia ut ullamco tempor ullamco non ullamco qui dolore in id. Quis minim ad et enim dolor adipisicing esse eu non eu amet nostrud.\r\n",
    registered: "2017-09-05T02:12:30 -02:00",
    latitude: 82.862302,
    longitude: -138.926681,
    tags: ["nulla", "dolor", "non", "ut", "aute", "sit", "amet"],
    friends: [
      {
        id: 0,
        name: "Marian Mcintyre",
      },
      {
        id: 1,
        name: "Ray Rosa",
      },
      {
        id: 2,
        name: "Page Patel",
      },
    ],
    greeting: "Hello, Cherry Chan! You have 10 unread messages.",
    favoriteFruit: "strawberry",
  },
];

export default DECLARATION;